/**
 * Nord Stage 4 value interpretation — discrete enum tables.
 *
 * Ported from ns4decode's ns4names.py (Randy, MIT — see THIRD_PARTY_LICENSES.md).
 * Each association (parameter name -> table) is VALIDATED against the regression
 * fixture's known-good CSV output. Formula/dependent interpreters (dB, Hz, BPM,
 * envelope times, synth category/wave) are NOT ported yet; those show raw ints.
 */

export const ENUM_TABLES: Record<string, Record<number, string>> = {
  AmpEQmode: { 0: "off", 1: "TWIN", 2: "TWIN variation", 3: "JC", 4: "JC variation", 5: "SMALL", 6: "SMALL variation", 7: "TO ROTARY", 8: "LP FILTER", 9: "HP FILTER" },
  ArpDirection: { 0: "UP", 1: "DOWN", 2: "UP/DOWN", 3: "RANDOM" },
  ArpMode: { 0: "Arp", 1: "Poly", 2: "Gate" },
  FXcompResponse: { 0: "normal", 1: "fast" },
  FXdelayEffects: { 0: "none", 1: "none", 2: "ENS", 3: "ENS variation", 4: "VIBE", 5: "VIBE variation", 6: "CHOR", 7: "CHOR variation", 8: "FLAM", 9: "FLAM variation", 10: "SPACE", 11: "SPACE variation" },
  FXdelayFilterType: { 0: "none", 1: "LP", 2: "HP", 3: "BP" },
  FXmod1mode: { 0: "A-PAN", 1: "A-PAN variation", 2: "TREM", 3: "TREM variation", 4: "RM", 5: "RM variation", 6: "A-WAH", 7: "A-WAH variation", 8: "WAH", 9: "WAH variation", 10: "PUMP", 11: "PUMP variation" },
  FXmod2mode: { 0: "PHAS", 1: "PHAS variation", 2: "FLANG", 3: "FLANG variation", 4: "CHOR", 5: "CHOR variation", 6: "VIBE", 7: "VIBE variation", 8: "ENS", 9: "ENS variation", 10: "SPIN", 11: "SPIN variation" },
  FXreverbDarkBright: { 0: "none", 1: "DARK", 2: "BRIGHT" },
  FXreverbType: { 0: "SPRING", 1: "SPRING variation", 2: "BOOTH", 3: "BOOTH variation", 4: "ROOM", 5: "ROOM variation", 6: "STAGE", 7: "STAGE variation", 8: "HALL", 9: "HALL variation", 10: "CATH", 11: "CATH variation" },
  FilterTrack: { 0: "off", 1: "1/3", 2: "2/3", 3: "3/3" },
  FilterType: { 0: "LP12", 1: "LP24", 2: "LPM", 3: "LPHP", 4: "BP", 5: "HP" },
  LFOshape: { 0: "triangle", 1: "saw", 2: "inv saw", 3: "square", 4: "S/H" },
  LFOtarget: { 0: "nothing", 1: "OSC CTRL", 2: "PITCH", 3: "FILTER" },
  Letter: { 0: "A", 1: "B", 2: "C", 3: "D", 4: "E", 5: "F", 6: "G", 7: "H" },
  OctaveShift: { 0: "0", 1: "+1", 2: "+2", 14: "-2", 15: "-1" },
  OnOff: { 0: "off", 1: "on" },
  PianoTouch: { 0: "heavy", 1: "med", 2: "light" },
  PianoType: { 0: "Grand", 1: "Upright", 2: "Electric", 3: "Clav", 4: "Digital", 5: "Misc" },
  PstickRng: { 0: "+/- 1", 1: "+/- 2", 2: "+/- 3", 3: "+/- 4", 4: "+/- 5", 5: "+/- 7", 6: "+/- 10", 7: "+/- 12", 8: "+2 / -12", 9: "+2 / -24" },
  RotaryStopPosition: { 0: "Free", 1: "Front Center", 2: "Front Left", 3: "Front Right", 4: "Back Left", 5: "Back Right", 6: "Back Center" },
  SampleAnalog: { 0: "samples", 1: "analog" },
  SampleOptions: { 0: "NATURAL", 1: "NO DYN", 2: "NO DYN & FAST ATK", 3: "FAST ATK" },
  VibratoOption: { 0: "none", 1: "ON", 2: "DLY", 3: "WHL", 4: "A.T.", 5: "PED" },
  VoicePriority: { 0: "no priority", 1: "LO", 2: "HI" },
};

/** Parameter name -> enum table. Validated against the fixture. */
export const PARAM_TABLE: Record<string, string> = {
  "FX amp sim/EQ mode": "AmpEQmode",
  "FX amp sim/EQ on/off": "OnOff",
  "FX comp global on/off": "OnOff",
  "FX comp on/off": "OnOff",
  "FX comp response": "FXcompResponse",
  "FX delay effects": "FXdelayEffects",
  "FX delay filter type": "FXdelayFilterType",
  "FX delay global on/off": "OnOff",
  "FX delay on/off": "OnOff",
  "FX delay ping pong on/off": "OnOff",
  "FX delay tempo MST CLK on/off": "OnOff",
  "FX mod 1 MST CLK on/off": "OnOff",
  "FX mod 1 mode": "FXmod1mode",
  "FX mod 1 on/off": "OnOff",
  "FX mod 2 mode": "FXmod2mode",
  "FX mod 2 on/off": "OnOff",
  "FX on/off": "OnOff",
  "FX reverb dark/bright": "FXreverbDarkBright",
  "FX reverb global on/off": "OnOff",
  "FX reverb on/off": "OnOff",
  "FX reverb type": "FXreverbType",
  "KB sync on/off": "OnOff",
  "KB zones 1-2 split point on/off": "OnOff",
  "KB zones 2-3 split point on/off": "OnOff",
  "KB zones 3-4 split point on/off": "OnOff",
  "LFO mst clk on/off": "OnOff",
  "LFO shape": "LFOshape",
  "LFO target": "LFOtarget",
  "arp MST CLK on/off": "OnOff",
  "arp direction": "ArpDirection",
  "arp pattern on/off": "OnOff",
  "arp zigzag on/off": "OnOff",
  "arpeggiator mode": "ArpMode",
  "arpeggiator run on/off": "OnOff",
  "bank": "Letter",
  "extern on/off": "OnOff",
  "filter on/off": "OnOff",
  "filter track": "FilterTrack",
  "filter type": "FilterType",
  "filter velocity on/off": "OnOff",
  "layer on/off": "OnOff",
  "legato on/off": "OnOff",
  "mono on/off": "OnOff",
  "octave shift": "OctaveShift",
  "organ FX amp sim/EQ on/off": "OnOff",
  "organ FX comp on/off": "OnOff",
  "organ FX delay on/off": "OnOff",
  "organ FX delay ping pong on/off": "OnOff",
  "organ FX delay tempo MST CLK on/off": "OnOff",
  "organ FX mod 1 MST CLK on/off": "OnOff",
  "organ FX mod 1 on/off": "OnOff",
  "organ FX mod 2 on/off": "OnOff",
  "organ FX reverb on/off": "OnOff",
  "organ pstick on/off": "OnOff",
  "organ rotary spkr on/off": "OnOff",
  "organ section on/off": "OnOff",
  "organ susped on/off": "OnOff",
  "osc env velocity on/off": "OnOff",
  "osc env-to-pitch on/off": "OnOff",
  "pedal noise on/off": "OnOff",
  "perc decay fast on/off": "OnOff",
  "perc harm 3rd on/off": "OnOff",
  "perc vol soft on/off": "OnOff",
  "percussion on/off": "OnOff",
  "piano section on/off": "OnOff",
  "piano type": "PianoType",
  "preset on/off": "OnOff",
  "program transpose on/off": "OnOff",
  "pstick on/off": "OnOff",
  "pstick rng": "PstickRng",
  "rotary spkr stop on/off": "OnOff",
  "rotary spkr stop position": "RotaryStopPosition",
  "sample bright on/off": "OnOff",
  "sample options": "SampleOptions",
  "samples/analog": "SampleAnalog",
  "soft rel on/off": "OnOff",
  "split on/off": "OnOff",
  "string res on/off": "OnOff",
  "susped on/off": "OnOff",
  "synth KB hold on/off": "OnOff",
  "synth arp group on/off": "OnOff",
  "synth section on/off": "OnOff",
  "touch": "PianoTouch",
  "vib/chorus on/off": "OnOff",
  "vibrato mode": "VibratoOption",
  "voice priority": "VoicePriority",
};
