// AUTO-GENERATED by scripts/gen_synth_analog.py from ns4decode_pkg (ns4names.py).
// DO NOT EDIT MANUALLY — re-run the generator if ns4decode's tables change.
//
// Supplements deps.generated.ts: the ANALOG (osc type 0) branch of
//   561-8 `analog cat (knob 2)`   key = "0:<rawCat>"
//   562-4 `analog wave (knob 3)`  key = "0:<rawCat>:<rawWave>"
// matching ns4decode's interpretSynthCategory / interpretSynthWave output.
// Ported from ns4decode (Randy, MIT — THIRD_PARTY_LICENSES.md).

export const ANALOG_CAT_561_8: Record<string, string> = {
    "0:0": "1 (PURE)",
    "0:1": "2 (SUB OSC)",
    "0:2": "3 (SYNC)",
    "0:3": "4 (SHAPE)",
    "0:4": "5 (SHAPE SINE)",
    "0:5": "6 (MULTI)",
    "0:6": "7 (SUPER)",
    "0:7": "8 (MISC)",
  };

export const ANALOG_WAVE_562_4: Record<string, string> = {
    "0:0:0": "1 (Pure Sine)",
    "0:0:1": "2 (Pure Triangle)",
    "0:0:2": "3 (Pure Saw)",
    "0:0:3": "4 (Pure Square)",
    "0:0:4": "5 (Pure Pulse 33)",
    "0:0:5": "6 (Pure Pulse 10)",
    "0:0:6": "7 (Pure White Noise)",
    "0:1:0": "1 (Sub Square Saw)",
    "0:1:1": "2 (Sub Pulse Saw)",
    "0:1:2": "3 (Sub Sine Saw)",
    "0:2:0": "1 (Sync Sine)",
    "0:2:1": "2 (Sync Triangle)",
    "0:2:2": "3 (Sync Saw)",
    "0:2:3": "4 (Sync Square)",
    "0:2:4": "5 (Sync Pulse 33)",
    "0:2:5": "6 (Sync Pulse 10)",
    "0:2:6": "7 (Sync Chop Saw 1)",
    "0:2:7": "8 (Sync Chop Saw 2)",
    "0:2:8": "9 (Sync Chop Square)",
    "0:3:0": "1 (Shape Triangle)",
    "0:3:1": "2 (Shape Saw)",
    "0:3:2": "3 (Shape Square)",
    "0:3:3": "4 (Shape Half Sine)",
    "0:3:4": "5 (Shape Parabolic)",
    "0:4:0": "1 (Shape Sine Saw)",
    "0:4:1": "2 (Shape Sine Square)",
    "0:4:2": "3 (Shape Sine Pulse)",
    "0:4:3": "4 (Shape Sine Squeeze)",
    "0:4:4": "5 (Shape Sine Fold)",
    "0:4:5": "6 (Shape Sine ESaw)",
    "0:4:6": "7 (Shape Sine ESquare)",
    "0:5:0": "1 (Multi Saw)",
    "0:5:1": "2 (Multi Saw 8ve)",
    "0:5:2": "3 (Multi Saw 5th)",
    "0:5:3": "4 (Multi Saw 5th+)",
    "0:5:4": "5 (Multi Saw 8ve 8ve+)",
    "0:5:5": "6 (Multi Saw 8ve 5th+)",
    "0:6:0": "1 (Super Saw)",
    "0:6:1": "2 (Super Square)",
    "0:6:2": "3 (Super Organ)",
    "0:6:3": "4 (Super Saw Bright)",
    "0:6:4": "5 (Super Square Bright)",
    "0:7:0": "1 (Pink Noise)",
    "0:7:1": "2 (Red Noise)",
    "0:7:2": "3 (Bell)",
  };
