import type { ProbeReport } from './probe';

const hex = (n: number) => '0x' + n.toString(16).padStart(4, '0');

/** A shareable Markdown summary of a read-only probe — what we found, no writes. */
export function probeReportMarkdown(r: ProbeReport): string {
  const rows = r.partitions.map((p) => `| ${p.index} | ${p.fileCount} |`).join('\n');
  return [
    `## Hardware validation: ${r.deviceName}`,
    '',
    `- Device: **${r.deviceName}** (USB ${hex(r.productId)})`,
    `- Captured: ${r.capturedAt}`,
    '',
    '| Partition | Files |',
    '| --- | --- |',
    rows,
    '',
    '_Generated by OpenNord — read-only probe (no data was written to the instrument)._',
  ].join('\n');
}

/** A pre-filled GitHub issue URL so an owner can contribute the report in one click.
 *  Uses encodeURIComponent (spaces → %20) so the title/body survive GitHub's parser. */
export function probeIssueUrl(r: ProbeReport): string {
  const title = `Hardware validation: ${r.deviceName} (${hex(r.productId)})`;
  const q =
    'labels=hardware-validation' +
    `&title=${encodeURIComponent(title)}` +
    `&body=${encodeURIComponent(probeReportMarkdown(r))}`;
  return `https://github.com/simonflore/opennord/issues/new?${q}`;
}
