#!/usr/bin/env python3
"""Generate the ANALOG-oscillator dependency tables for the NS4 synth.

The committed deps.generated.ts (ported from ns4decode) covers oscillator types
FM-H / FM-I / WAVE for `analog cat (knob 2)` (561-8) and `analog wave (knob 3)`
(562-4), but is MISSING the ANALOG (type 0) branch — so those render as raw ints.

This regenerates just the ANALOG entries directly from ns4decode's own name
tables, matching its interpretSynthCategory / interpretSynthWave output exactly
(see ns4decode.py). Source: ns4decode_pkg (Randy, MIT — THIRD_PARTY_LICENSES.md).

Get the source package (MIT):
    curl -sL -o /tmp/ns4decode_pkg.zip \
        https://ns4decode.netlify.app/downloads/ns4decode_pkg.zip
    unzip -o /tmp/ns4decode_pkg.zip -d /tmp

Usage:
    python3 scripts/gen_synth_analog.py /tmp/ns4decode_pkg > \
        src/lib/ns4/synth-analog.generated.ts

Note: like the existing port, this bakes in the *new* (current-firmware) tables;
older files used SynthCategoryOld/SynthWaveOld (pre-"SynthTypes" version change).
"""
import sys
import importlib.util


def load(pkg_dir):
    spec = importlib.util.spec_from_file_location("ns4names", f"{pkg_dir}/ns4names.py")
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m


def main():
    pkg = sys.argv[1] if len(sys.argv) > 1 else "/tmp/ns4decode_pkg"
    n = load(pkg)

    ANALOG = "ANALOG"  # SynthType[0]
    cat_map = n.SynthCategory[ANALOG]            # rawCat -> CATEGORY NAME
    # interpretSynthCategory (ANALOG): f"{raw+1} ({name})"
    cat_entries = {f"0:{raw}": f"{raw + 1} ({name})" for raw, name in sorted(cat_map.items())}

    # interpretSynthWave (ANALOG): cat name -> SynthWave[name][rawWave] -> f"{raw+1} ({name})"
    wave_entries = {}
    for craw, cname in sorted(cat_map.items()):
        waves = n.SynthWave.get(cname, {})
        for wraw, wname in sorted(waves.items()):
            wave_entries[f"0:{craw}:{wraw}"] = f"{wraw + 1} ({wname})"

    def emit(d):
        return "{\n" + "".join(f'    "{k}": {js_str(v)},\n' for k, v in d.items()) + "  }"

    def js_str(s):
        return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

    print("""// AUTO-GENERATED by scripts/gen_synth_analog.py from ns4decode_pkg (ns4names.py).
// DO NOT EDIT MANUALLY — re-run the generator if ns4decode's tables change.
//
// Supplements deps.generated.ts: the ANALOG (osc type 0) branch of
//   561-8 `analog cat (knob 2)`   key = "0:<rawCat>"
//   562-4 `analog wave (knob 3)`  key = "0:<rawCat>:<rawWave>"
// matching ns4decode's interpretSynthCategory / interpretSynthWave output.
// Ported from ns4decode (Randy, MIT — THIRD_PARTY_LICENSES.md).

export const ANALOG_CAT_561_8: Record<string, string> = """ + emit(cat_entries) + """;

export const ANALOG_WAVE_562_4: Record<string, string> = """ + emit(wave_entries) + ";")


if __name__ == "__main__":
    main()
