/**
 * Curated per-model decode progress — the checked-in "state" you maintain as you
 * process contribution bundles. No backend: localize a control to its bytes,
 * add an entry here, and the coverage map (contribute landing + compatibility
 * matrix) updates.
 *
 * Workflow: open a contribution JSON, decide which body bytes a labeled change
 * occupies (the bundle already gives candidate `ranges` per entry), then add a
 * `MappedControl`. `bodyBytes` is the model's body size — read it from any export
 * (file length − 44-byte CBIN header) the first time you touch a model.
 *
 * Stage 4 is NOT listed here — it's fully decoded from the offset map already.
 */

export interface MappedControl {
  /** What the control is, e.g. "Filter cutoff" or "CC 70". */
  label: string;
  /** Body-relative byte ranges it occupies (same shape as a contribution entry). */
  ranges: Array<{ start: number; end: number }>;
}

/**
 * A named byte region for the body-coverage visual map.
 * `constant`  — same value across corpus (structural padding / fixed fields).
 * `confirmed` — mapped to a named control with known encoding.
 * `candidate` — section identified but individual field bits not yet pinned.
 * `unknown`   — varies in the corpus but not yet attributed to a section.
 */
export type RegionStatus = 'constant' | 'confirmed' | 'candidate' | 'unknown';

export interface BodyRegion {
  start: number;
  end: number;
  label: string;
  status: RegionStatus;
}

export interface ModelProgress {
  /** Total body size in bytes (file length − 44). null until a file is measured. */
  bodyBytes: number | null;
  /** Controls localized to bytes so far. */
  controls: MappedControl[];
  /** Named byte regions for the coverage visual map (optional). */
  regions?: BodyRegion[];
}

// Keyed by model id (clavia/partitions.ts). Add models + controls as you process
// contributions. Example (delete when you add a real one):
//   'electro-6': {
//     bodyBytes: 1234,
//     controls: [{ label: 'Organ drawbar 1', ranges: [{ start: 39, end: 39 }] }],
//   },
export const MODEL_PROGRESS: Record<string, ModelProgress> = {
  'electro-6': {
    bodyBytes: 211,
    controls: [
      { label: 'Upper drawbars (9 bars)', ranges: [{ start: 143, end: 147 }] },
      { label: 'Lower drawbars (9 bars)', ranges: [{ start: 158, end: 162 }] },
      { label: 'LFO / synth enable',      ranges: [{ start: 39,  end: 39  }] },
      { label: 'LFO rate + depth (16-bit)',ranges: [{ start: 7,   end: 8   }] },
      { label: 'Piano vibrato apply',      ranges: [{ start: 73,  end: 73  }] },
      { label: 'Global LFO active flag',   ranges: [{ start: 6,   end: 6   }] },
      { label: 'Sample model ID (32-bit, candidate)',          ranges: [{ start: 40,  end: 44  }] },
      { label: 'Sample section header (type/slot/variation)',  ranges: [{ start: 38,  end: 39  }] },
      { label: 'Organ lead-in (KB zones/octave/model/preset)', ranges: [{ start: 124, end: 125 }] },
      { label: 'Organ / sample section enable flags',          ranges: [{ start: 5,   end: 6   }] },
    ],
    regions: [
      { start: 0,   end: 4,   label: 'Header prefix',            status: 'constant'  },
      { start: 5,   end: 6,   label: 'Organ / sample section enable flags', status: 'candidate' },
      { start: 7,   end: 8,   label: 'Global / LFO params',      status: 'candidate' },
      { start: 9,   end: 19,  label: '',                          status: 'constant'  },
      { start: 20,  end: 28,  label: 'Organ control (B)',         status: 'candidate' },
      { start: 29,  end: 37,  label: '',                          status: 'constant'  },
      { start: 38,  end: 39,  label: 'Sample section header (type/slot/variation)', status: 'candidate' },
      { start: 40,  end: 44,  label: 'Sample model ID (32-bit)', status: 'candidate' },
      { start: 45,  end: 50,  label: 'Synth / mod engine (C)',    status: 'candidate' },
      { start: 51,  end: 61,  label: '',                          status: 'constant'  },
      { start: 62,  end: 75,  label: 'Piano section (D)',         status: 'candidate' },
      { start: 76,  end: 93,  label: '',                          status: 'constant'  },
      { start: 94,  end: 94,  label: 'Unknown flag',              status: 'unknown'   },
      { start: 95,  end: 103, label: '',                          status: 'constant'  },
      { start: 104, end: 104, label: 'Section flag',              status: 'unknown'   },
      { start: 105, end: 113, label: '',                          status: 'constant'  },
      { start: 114, end: 114, label: 'Section flag',              status: 'unknown'   },
      { start: 115, end: 123, label: '',                          status: 'constant'  },
      { start: 124, end: 125, label: 'Organ lead-in (KB zones/octave/model/preset)', status: 'candidate' },
      { start: 126, end: 142, label: '',                          status: 'constant'  },
      { start: 143, end: 147, label: 'Upper drawbars',            status: 'confirmed' },
      { start: 148, end: 157, label: '',                          status: 'constant'  },
      { start: 158, end: 162, label: 'Lower drawbars',            status: 'confirmed' },
      { start: 163, end: 185, label: '',                          status: 'constant'  },
      { start: 186, end: 186, label: 'Unknown flag',              status: 'unknown'   },
      { start: 187, end: 200, label: '',                          status: 'constant'  },
      { start: 201, end: 201, label: 'Unknown flag',              status: 'unknown'   },
      { start: 202, end: 210, label: '',                          status: 'constant'  },
    ],
  },
  'lead-a1': {
    bodyBytes: 79,
    controls: [
      { label: 'Body header (high nibble of body[0])',                ranges: [{ start: 0,  end: 0  }] },
      { label: '7-bit packed parameter stream',                       ranges: [{ start: 0,  end: 76 }] },
      { label: 'Oscillator + filter block (candidate)',               ranges: [{ start: 0,  end: 15 }] },
      { label: 'Amp + mod/filter envelope block (candidate)',         ranges: [{ start: 16, end: 31 }] },
      { label: 'LFO / arpeggiator block (candidate)',                 ranges: [{ start: 33, end: 47 }] },
      { label: 'Effects + voice/global block (candidate)',            ranges: [{ start: 51, end: 76 }] },
      { label: 'Body checksum (16-bit)',                              ranges: [{ start: 77, end: 78 }] },
    ],
    regions: [
      { start: 0,  end: 0,  label: '4-bit header + start of 7-bit param stream', status: 'confirmed' },
      { start: 1,  end: 15, label: 'Osc+filter candidate cluster',               status: 'candidate' },
      { start: 16, end: 31, label: 'Envelope candidate cluster (ADSR)',          status: 'candidate' },
      { start: 32, end: 32, label: '',                                           status: 'constant'  },
      { start: 33, end: 47, label: 'LFO/arp candidate cluster',                  status: 'candidate' },
      { start: 48, end: 50, label: '',                                           status: 'constant'  },
      { start: 51, end: 52, label: 'FX/voice candidate',                         status: 'candidate' },
      { start: 53, end: 53, label: '',                                           status: 'constant'  },
      { start: 54, end: 60, label: 'FX/voice candidate cluster',                 status: 'candidate' },
      { start: 61, end: 61, label: '',                                           status: 'constant'  },
      { start: 62, end: 70, label: 'FX/voice candidate cluster',                 status: 'candidate' },
      { start: 71, end: 71, label: '',                                           status: 'constant'  },
      { start: 72, end: 73, label: 'Global/voice candidate',                     status: 'candidate' },
      { start: 74, end: 75, label: '',                                           status: 'constant'  },
      { start: 76, end: 76, label: 'Tail param/flag bits',                       status: 'candidate' },
      { start: 77, end: 78, label: '16-bit body checksum',                       status: 'confirmed' },
    ],
  },
  'lead-4': {
    bodyBytes: 299,
    controls: [
      { label: 'CBIN checksum (2-byte LE trailer)',                          ranges: [{ start: 297, end: 298 }] },
      { label: 'Cluster B head selector (osc/voice mode, 2-bit enum)',       ranges: [{ start: 30,  end: 30  }] },
      { label: 'Main synth voice (2 osc, filter, 2 env, 2 LFO; bit-packed)', ranges: [{ start: 31,  end: 88  }] },
      { label: 'Voice block packed tail',                                    ranges: [{ start: 89,  end: 102 }] },
      { label: 'Cluster C enable flag (arp/section on-off)',                 ranges: [{ start: 239, end: 239 }] },
      { label: 'Cluster C enum A (LFO/arp mode, 8 values)',                  ranges: [{ start: 245, end: 245 }] },
      { label: 'Cluster C enum B (FX/filter type, ~8 values)',              ranges: [{ start: 248, end: 248 }] },
      { label: 'FX / arp / morph block (bit-packed)',                        ranges: [{ start: 240, end: 264 }] },
    ],
    regions: [
      { start: 0,   end: 18,  label: 'Cluster A - header/category/global',     status: 'candidate' },
      { start: 19,  end: 19,  label: 'Cluster A field (version/enable flag)',  status: 'candidate' },
      { start: 20,  end: 21,  label: 'Cluster A packed fields',               status: 'candidate' },
      { start: 22,  end: 23,  label: 'Anchor/magic 0x80 0x5e (separator)',     status: 'candidate' },
      { start: 24,  end: 24,  label: 'Cluster A trailing packed byte',         status: 'candidate' },
      { start: 25,  end: 29,  label: '',                                       status: 'constant'  },
      { start: 30,  end: 30,  label: 'Cluster B head selector (2-bit enum)',   status: 'candidate' },
      { start: 31,  end: 88,  label: 'Main synth voice (bit-packed)',          status: 'candidate' },
      { start: 89,  end: 102, label: 'Voice packed tail',                      status: 'candidate' },
      { start: 103, end: 237, label: '',                                       status: 'constant'  },
      { start: 238, end: 238, label: 'Cluster C head byte',                    status: 'candidate' },
      { start: 239, end: 239, label: 'Cluster C enable flag (arp/section)',    status: 'candidate' },
      { start: 240, end: 244, label: 'FX/arp packed fields',                   status: 'candidate' },
      { start: 245, end: 245, label: 'Cluster C enum A (LFO/arp mode)',        status: 'candidate' },
      { start: 246, end: 246, label: 'Cluster C packed field',                 status: 'candidate' },
      { start: 247, end: 247, label: '',                                       status: 'constant'  },
      { start: 248, end: 248, label: 'Cluster C enum B (FX/filter type)',      status: 'candidate' },
      { start: 249, end: 264, label: 'FX/arp/morph packed block',              status: 'candidate' },
      { start: 265, end: 296, label: '',                                       status: 'constant'  },
      { start: 297, end: 298, label: 'CBIN checksum (2-byte LE trailer)',      status: 'confirmed' },
    ],
  },
  'electro-4': {
    bodyBytes: 92,
    controls: [
      { label: 'Organ drawbars (preset 1, default slot)',      ranges: [{ start: 4,  end: 8  }] },
      { label: 'Organ drawbars (preset 2 / edited, active)',   ranges: [{ start: 16, end: 20 }] },
      { label: 'Organ drawbars (second default slot)',         ranges: [{ start: 25, end: 29 }] },
      { label: 'Organ section extra params (post-drawbar)',     ranges: [{ start: 20, end: 21 }] },
      { label: 'Section enable / program flags',               ranges: [{ start: 0,  end: 0  }] },
      { label: 'Sample reference ID (candidate)',              ranges: [{ start: 37, end: 41 }] },
      { label: 'Sample voice / zone params (candidate)',       ranges: [{ start: 43, end: 44 }] },
      { label: 'Secondary program params',                     ranges: [{ start: 51, end: 63 }] },
      { label: 'Level / mode byte (tail0)',                    ranges: [{ start: 68, end: 68 }] },
      { label: 'Level / mode byte (tail1)',                    ranges: [{ start: 79, end: 79 }] },
      { label: 'Program-specific tail bytes',                  ranges: [{ start: 90, end: 91 }] },
    ],
    regions: [
      { start: 0,  end: 0,  label: 'Section enable / program flags',                       status: 'candidate' },
      { start: 1,  end: 3,  label: 'Constant section header A',                            status: 'constant'  },
      { start: 4,  end: 8,  label: 'Organ drawbars (preset 1, 9 nibbles)',                status: 'confirmed' },
      { start: 9,  end: 15, label: 'Constant section header A tail',                       status: 'constant'  },
      { start: 16, end: 20, label: 'Organ drawbars (preset 2 / edited, 9 nibbles)',       status: 'confirmed' },
      { start: 20, end: 21, label: 'Organ vib/chorus + percussion flags',                 status: 'candidate' },
      { start: 22, end: 24, label: 'Constant section header B',                            status: 'constant'  },
      { start: 25, end: 29, label: 'Organ drawbars (second default slot, 9 nibbles)',     status: 'confirmed' },
      { start: 30, end: 36, label: 'Constant section header B tail',                       status: 'constant'  },
      { start: 37, end: 41, label: 'Sample reference ID (high-entropy)',                  status: 'candidate' },
      { start: 42, end: 42, label: 'Sample section param',                                status: 'unknown'   },
      { start: 43, end: 44, label: 'Sample voice / zone params',                          status: 'candidate' },
      { start: 45, end: 45, label: 'Sample section param',                                status: 'unknown'   },
      { start: 46, end: 50, label: 'Constant zero padding',                                status: 'constant'  },
      { start: 51, end: 63, label: 'Secondary program parameters',                         status: 'candidate' },
      { start: 64, end: 67, label: 'Constant zero padding',                                status: 'constant'  },
      { start: 68, end: 68, label: 'Level / mode byte tail0 (bit-3 flag in lo nibble)',    status: 'candidate' },
      { start: 69, end: 78, label: 'Constant zero padding',                                status: 'constant'  },
      { start: 79, end: 79, label: 'Level / mode byte tail1 (hi nibble 0-13)',             status: 'candidate' },
      { start: 80, end: 89, label: 'Constant zero padding',                                status: 'constant'  },
      { start: 90, end: 91, label: 'Program-specific bytes (unique per program)',           status: 'unknown'   },
    ],
  },

  'electro-5': {
    bodyBytes: 103,
    controls: [
      { label: 'Upper drawbars (preset 1, primary)',          ranges: [{ start: 21, end: 25 }] },
      { label: 'Lower drawbars (preset 1, primary)',          ranges: [{ start: 28, end: 32 }] },
      { label: 'Upper drawbars (preset 2)',                   ranges: [{ start: 39, end: 43 }] },
      { label: 'Lower drawbars (preset 2)',                   ranges: [{ start: 45, end: 49 }] },
      { label: 'Pedal drawbars (9 bars, candidate)',          ranges: [{ start: 55, end: 59 }] },
      { label: 'Piano / sample section active (byte17 bit7)',  ranges: [{ start: 17, end: 17 }] },
      { label: 'Piano / sample model ID (high-entropy)',       ranges: [{ start: 7,  end: 12 }] },
      { label: 'Program type flags',                          ranges: [{ start: 0,  end: 0  }] },
      { label: 'Section enable nibble',                       ranges: [{ start: 6,  end: 6  }] },
      { label: 'Sample-section descriptor record (candidate)', ranges: [{ start: 83, end: 94 }] },
      { label: 'Trailing checksum / CRC (candidate)',          ranges: [{ start: 101, end: 102 }] },
    ],
    regions: [
      { start: 0,   end: 0,   label: 'Program type flags (9 unique values)',              status: 'candidate' },
      { start: 1,   end: 5,   label: 'Constant 0x00',                                    status: 'constant'  },
      { start: 6,   end: 6,   label: 'Section enable nibble (0x01/0x00/0x40/0x27)',      status: 'candidate' },
      { start: 7,   end: 12,  label: 'Piano / sample model ID (6 bytes, high-entropy)',   status: 'confirmed' },
      { start: 13,  end: 13,  label: 'Single-bit flag (0x80 or 0x00)',                   status: 'candidate' },
      { start: 14,  end: 16,  label: 'Constant 0x00',                                    status: 'constant'  },
      { start: 17,  end: 17,  label: 'Piano / sample section active (bit7)',              status: 'confirmed' },
      { start: 18,  end: 18,  label: 'Constant 0x00',                                    status: 'constant'  },
      { start: 19,  end: 19,  label: 'Flag nibble (0x00 or 0x40)',                       status: 'candidate' },
      { start: 20,  end: 20,  label: 'Constant 0x00',                                    status: 'constant'  },
      { start: 21,  end: 25,  label: 'Upper drawbars (preset 1, 9 nibbles, primary)',     status: 'confirmed' },
      { start: 26,  end: 26,  label: 'Sub-field nibble (0x20/0x00/0x14)',                status: 'candidate' },
      { start: 27,  end: 27,  label: 'Constant 0x00',                                    status: 'constant'  },
      { start: 28,  end: 32,  label: 'Lower drawbars (preset 1, 9 nibbles, primary)',     status: 'confirmed' },
      { start: 33,  end: 33,  label: 'Sub-field nibble (0x20 or 0x00)',                  status: 'candidate' },
      { start: 34,  end: 34,  label: 'Constant 0x00',                                    status: 'constant'  },
      { start: 35,  end: 35,  label: 'Nibble flag',                                      status: 'candidate' },
      { start: 36,  end: 38,  label: 'Constant 0x00',                                    status: 'constant'  },
      { start: 39,  end: 43,  label: 'Upper drawbars (preset 2, 9 nibbles)',             status: 'confirmed' },
      { start: 44,  end: 44,  label: 'Constant 0x00',                                    status: 'constant'  },
      { start: 45,  end: 49,  label: 'Lower drawbars (preset 2, 9 nibbles)',             status: 'confirmed' },
      { start: 50,  end: 50,  label: 'Constant 0x00',                                    status: 'constant'  },
      { start: 51,  end: 51,  label: 'Nibble field',                                     status: 'candidate' },
      { start: 52,  end: 54,  label: 'Constant 0x00',                                    status: 'constant'  },
      { start: 55,  end: 59,  label: 'Pedal drawbars (9 nibbles, candidate)',             status: 'candidate' },
      { start: 60,  end: 60,  label: 'Constant 0x00',                                    status: 'constant'  },
      { start: 61,  end: 61,  label: 'Nibble flag (0x8 or 0x0 in hi bit)',               status: 'candidate' },
      { start: 62,  end: 70,  label: 'Constant 0x00',                                    status: 'constant'  },
      { start: 71,  end: 74,  label: 'Extra nibble group',                               status: 'candidate' },
      { start: 75,  end: 75,  label: 'Constant 0x08 sentinel',                           status: 'constant'  },
      { start: 76,  end: 76,  label: 'Constant 0x00',                                    status: 'constant'  },
      { start: 77,  end: 77,  label: 'Nibble flag (0x8 or 0x0)',                         status: 'candidate' },
      { start: 78,  end: 80,  label: 'Constant 0x00',                                    status: 'constant'  },
      { start: 81,  end: 81,  label: 'Constant 0x08 sentinel',                           status: 'constant'  },
      { start: 82,  end: 82,  label: 'Constant 0x00',                                    status: 'constant'  },
      { start: 83,  end: 94,  label: 'Sample-section descriptor record (bank ref + hash)',  status: 'candidate' },
      { start: 95,  end: 97,  label: 'Sample reference block tail (3 bytes)',             status: 'unknown'   },
      { start: 98,  end: 100, label: 'Constant 0x00',                                    status: 'constant'  },
      { start: 101, end: 102, label: 'Trailing checksum / CRC (2 bytes)',                 status: 'candidate' },
    ],
  },

  'piano-4': {
    bodyBytes: 90,
    controls: [
      { label: 'Piano family flag: 0x80=EP, 0x00=Grand',        ranges: [{ start: 25, end: 25 }] },
      { label: 'Piano family redundant flag: 0x0c=EP, 0x90=Grand', ranges: [{ start: 72, end: 72 }] },
      { label: 'Piano model ID (byte19 family selector + 4-byte hash)', ranges: [{ start: 19, end: 23 }] },
      { label: 'Piano output level (0-127, candidate)',          ranges: [{ start: 35, end: 35 }] },
      { label: 'Velocity curve (bits 7-6, 2-bit enum, candidate)', ranges: [{ start: 36, end: 36 }] },
      { label: 'FX-mod word (FX sub-block head, candidate)',     ranges: [{ start: 59, end: 60 }] },
      { label: 'FX modulation params (rate/amount/mode, candidate)', ranges: [{ start: 66, end: 69 }] },
    ],
    regions: [
      { start: 0,  end: 2,  label: 'Constant zero pad',                                        status: 'constant'  },
      { start: 3,  end: 3,  label: 'Format marker 0x64 (version 1.00×100)',                    status: 'constant'  },
      { start: 4,  end: 4,  label: 'Constant 0x0b',                                            status: 'constant'  },
      { start: 5,  end: 5,  label: 'Constant 0x01',                                            status: 'constant'  },
      { start: 6,  end: 6,  label: 'Constant 0x80',                                            status: 'constant'  },
      { start: 7,  end: 7,  label: 'Constant 0x40',                                            status: 'constant'  },
      { start: 8,  end: 16, label: 'Constant header tail',                                     status: 'constant'  },
      { start: 17, end: 18, label: 'Per-program params (transpose / tuning candidate)',         status: 'unknown'   },
      { start: 19, end: 23, label: 'Piano model ID (byte19 family selector + 4-byte hash; George=Tea)', status: 'confirmed' },
      { start: 24, end: 24, label: 'Per-program variation param',                              status: 'unknown'   },
      { start: 25, end: 25, label: 'Piano family flag: 0x80=EP, 0x00=Grand',                   status: 'confirmed' },
      { start: 26, end: 33, label: 'Constant zero pad',                                        status: 'constant'  },
      { start: 34, end: 34, label: 'Constant 0x17 (section-length marker)',                    status: 'constant'  },
      { start: 35, end: 35, label: 'Piano output level (7-bit, 0-127 scale)',                  status: 'candidate' },
      { start: 36, end: 36, label: 'Velocity curve (bits 7-6) + unknown low bits',             status: 'candidate' },
      { start: 37, end: 47, label: 'Piano engine params (pedal noise / string res / release)',  status: 'unknown'   },
      { start: 48, end: 57, label: 'Constant zero pad',                                        status: 'constant'  },
      { start: 58, end: 58, label: 'Constant 0x1f (section-length marker)',                    status: 'constant'  },
      { start: 59, end: 60, label: 'FX-mod word (FX sub-block head; 0x0202=off DISPROVEN)',       status: 'candidate' },
      { start: 61, end: 65, label: 'Effect type / intensity params',                           status: 'unknown'   },
      { start: 66, end: 69, label: 'FX modulation params (rate/amount/mode candidate)',          status: 'candidate' },
      { start: 70, end: 70, label: 'Output param (narrow range 206-211)',                      status: 'unknown'   },
      { start: 71, end: 71, label: 'Output / routing param (widely varying)',                  status: 'unknown'   },
      { start: 72, end: 72, label: 'Piano family redundant flag: 0x0c=EP, 0x90=Grand',         status: 'confirmed' },
      { start: 73, end: 89, label: 'Constant zero tail',                                       status: 'constant'  },
    ],
  },

  'piano-5': {
    bodyBytes: 237,
    controls: [
      { label: 'Layer B active (bit 3 of body[7])',             ranges: [{ start: 7,   end: 7   }] },
      { label: 'Sound A piano model ID (32-bit)',               ranges: [{ start: 61,  end: 64  }] },
      { label: 'Sound B piano model ID (32-bit)',               ranges: [{ start: 93,  end: 96  }] },
      { label: 'Sound A volume (7-bit, candidate)',             ranges: [{ start: 58,  end: 58  }] },
      { label: 'Sound B volume (7-bit, candidate)',             ranges: [{ start: 90,  end: 90  }] },
      { label: 'Sound A piano type (3-bit enum, candidate)',    ranges: [{ start: 60,  end: 60  }] },
      { label: 'FX A transpose / octave (candidate)',           ranges: [{ start: 134, end: 134 }] },
      { label: 'Primary program parameters',                   ranges: [{ start: 18,  end: 32  }] },
      { label: 'Layer A sound slot (9 bytes)',                 ranges: [{ start: 58,  end: 66  }] },
      { label: 'Layer B sound slot (9 bytes)',                 ranges: [{ start: 90,  end: 98  }] },
      { label: 'Layer A effects / EQ parameters (14 bytes)',   ranges: [{ start: 122, end: 135 }] },
      { label: 'Layer B effects / EQ parameters (14 bytes)',   ranges: [{ start: 180, end: 193 }] },
    ],
    regions: [
      { start: 0,   end: 2,   label: 'Constant zero pad',                                          status: 'constant'  },
      { start: 3,   end: 4,   label: 'Format tag 0x65 0x0c (NP5 body sub-format)',                 status: 'constant'  },
      { start: 5,   end: 6,   label: 'Cluster A: program header',                                  status: 'candidate' },
      { start: 7,   end: 7,   label: 'Layer B active (bit 3)',                                     status: 'confirmed' },
      { start: 8,   end: 16,  label: 'Constant zero pad',                                          status: 'constant'  },
      { start: 17,  end: 17,  label: 'Constant magic 0x27 (39 decimal)',                           status: 'constant'  },
      { start: 18,  end: 32,  label: 'Cluster B: primary program params',                          status: 'candidate' },
      { start: 33,  end: 56,  label: 'Constant zero pad',                                          status: 'constant'  },
      { start: 57,  end: 57,  label: 'Record marker 0x1f (layer A sound slot)',                    status: 'constant'  },
      { start: 58,  end: 58,  label: 'Sound A volume (7-bit)',                                     status: 'candidate' },
      { start: 59,  end: 59,  label: 'Cluster C: layer A sound param',                             status: 'candidate' },
      { start: 60,  end: 60,  label: 'Sound A piano type (3-bit enum)',                            status: 'candidate' },
      { start: 61,  end: 64,  label: 'Sound A piano model ID (32-bit)',                            status: 'confirmed' },
      { start: 65,  end: 66,  label: 'Cluster C: layer A sound params tail',                       status: 'candidate' },
      { start: 67,  end: 88,  label: 'Constant zero pad',                                          status: 'constant'  },
      { start: 89,  end: 89,  label: 'Record marker 0x1f (layer B sound slot)',                    status: 'constant'  },
      { start: 90,  end: 90,  label: 'Sound B volume (7-bit)',                                     status: 'candidate' },
      { start: 91,  end: 92,  label: 'Cluster D: layer B sound params',                            status: 'candidate' },
      { start: 93,  end: 96,  label: 'Sound B piano model ID (32-bit)',                            status: 'confirmed' },
      { start: 97,  end: 98,  label: 'Cluster D: layer B sound params tail',                       status: 'candidate' },
      { start: 99,  end: 120, label: 'Constant zero pad',                                          status: 'constant'  },
      { start: 121, end: 121, label: 'Record marker 0x39 (layer A FX slot)',                       status: 'constant'  },
      { start: 122, end: 133, label: 'Cluster E: layer A FX / EQ params',                          status: 'candidate' },
      { start: 134, end: 134, label: 'FX A transpose / octave (sub-byte enum)',                    status: 'candidate' },
      { start: 135, end: 135, label: 'Cluster E: layer A FX / EQ params tail',                     status: 'candidate' },
      { start: 136, end: 178, label: 'Constant zero pad',                                          status: 'constant'  },
      { start: 179, end: 179, label: 'Record marker 0x39 (layer B FX slot)',                       status: 'constant'  },
      { start: 180, end: 193, label: 'Cluster F: layer B FX / EQ params (14 bytes)',               status: 'candidate' },
      { start: 194, end: 236, label: 'Constant zero pad',                                          status: 'constant'  },
    ],
  },

  'grand-2': {
    bodyBytes: 185,
    controls: [
      // Layer A piano cluster (bytes 22-30 = body bits 176-247). Confirmed sub-fields:
      { label: 'Layer A piano on (bit)',                       ranges: [{ start: 22,  end: 22  }] },
      { label: 'Layer A volume (7-bit)',                       ranges: [{ start: 22,  end: 23  }] },
      { label: 'Layer A KB zones (4-bit)',                     ranges: [{ start: 23,  end: 23  }] },
      { label: 'Layer A octave shift (4-bit)',                 ranges: [{ start: 23,  end: 24  }] },
      { label: 'Layer A piano type (3-bit enum)',              ranges: [{ start: 24,  end: 24  }] },
      { label: 'Layer A piano model ID (32-bit)',              ranges: [{ start: 25,  end: 29  }] },
      // Layer B piano cluster (bytes 36-44 = body bits 288-359). Confirmed sub-fields:
      { label: 'Layer B piano on (bit)',                       ranges: [{ start: 36,  end: 36  }] },
      { label: 'Layer B volume (7-bit)',                       ranges: [{ start: 36,  end: 37  }] },
      { label: 'Layer B KB zones (4-bit)',                     ranges: [{ start: 37,  end: 37  }] },
      { label: 'Layer B octave shift (4-bit)',                 ranges: [{ start: 37,  end: 38  }] },
      { label: 'Layer B piano type (3-bit enum)',              ranges: [{ start: 38,  end: 38  }] },
      { label: 'Layer B piano model ID (32-bit)',              ranges: [{ start: 39,  end: 43  }] },
      { label: 'Layer B active / extended mode flag (bit7)',    ranges: [{ start: 8,   end: 8   }] },
      { label: 'Global parameter 1 (top 3 bits)',              ranges: [{ start: 16,  end: 16  }] },
      { label: 'Global parameter 2 (top 3 bits)',              ranges: [{ start: 94,  end: 94  }] },
      { label: 'Layer A piano params tail (candidate sub-fields)', ranges: [{ start: 29,  end: 30  }] },
      { label: 'Layer B piano params tail (candidate sub-fields)', ranges: [{ start: 43,  end: 44  }] },
      { label: 'Layer A extended params (16 bytes)',           ranges: [{ start: 50,  end: 65  }] },
      { label: 'Layer B extended params (16 bytes)',           ranges: [{ start: 72,  end: 87  }] },
      { label: 'Layer A effects / audio params (14 bytes)',    ranges: [{ start: 100, end: 113 }] },
      { label: 'Layer B effects / audio params (14 bytes)',    ranges: [{ start: 121, end: 134 }] },
      { label: 'Layer A final section (16 bytes)',             ranges: [{ start: 142, end: 157 }] },
      { label: 'Layer B final section (16 bytes)',             ranges: [{ start: 164, end: 179 }] },
    ],
    regions: [
      { start: 0,   end: 4,   label: 'Constant preamble',                                       status: 'constant'  },
      { start: 5,   end: 8,   label: 'Global header cluster A (4 bytes)',                       status: 'candidate' },
      { start: 9,   end: 15,  label: 'Separator tag 0x05 section 1',                           status: 'constant'  },
      { start: 16,  end: 16,  label: 'Global param 1 (top 3 bits, values 0-7)',                 status: 'candidate' },
      { start: 17,  end: 21,  label: 'Separator tag 0x0d layer A',                             status: 'constant'  },
      { start: 22,  end: 29,  label: 'Layer A piano core (on/vol/zones/octave/type/model ID)', status: 'confirmed' },
      { start: 30,  end: 30,  label: 'Layer A piano params tail (pstick..timbre candidate)',   status: 'candidate' },
      { start: 31,  end: 35,  label: 'Separator tag 0x0d layer B',                             status: 'constant'  },
      { start: 36,  end: 43,  label: 'Layer B piano core (on/vol/zones/octave/type/model ID)', status: 'confirmed' },
      { start: 44,  end: 44,  label: 'Layer B piano params tail (pstick..timbre candidate)',   status: 'candidate' },
      { start: 45,  end: 49,  label: 'Separator tag 0x15 layer A extended',                    status: 'constant'  },
      { start: 50,  end: 65,  label: 'Layer A extended params cluster C1 (16 bytes)',           status: 'candidate' },
      { start: 66,  end: 71,  label: 'Separator tag 0x15 layer B extended',                    status: 'constant'  },
      { start: 72,  end: 87,  label: 'Layer B extended params cluster C2 (16 bytes)',           status: 'candidate' },
      { start: 88,  end: 93,  label: 'Separator tag 0x05 section 2',                           status: 'constant'  },
      { start: 94,  end: 94,  label: 'Global param 2 (top 3 bits, values 0-7)',                 status: 'candidate' },
      { start: 95,  end: 99,  label: 'Separator tag 0x14 layer A effects',                     status: 'constant'  },
      { start: 100, end: 113, label: 'Layer A effects cluster D1 (14 bytes; [1]=piano model)', status: 'candidate' },
      { start: 114, end: 120, label: 'Separator tag 0x14 layer B effects',                     status: 'constant'  },
      { start: 121, end: 134, label: 'Layer B effects cluster D2 (14 bytes; [1]=piano model)', status: 'candidate' },
      { start: 135, end: 141, label: 'Separator tag 0x15 layer A final',                       status: 'constant'  },
      { start: 142, end: 157, label: 'Layer A final cluster E1 (16 bytes)',                    status: 'candidate' },
      { start: 158, end: 163, label: 'Separator tag 0x15 layer B final',                       status: 'constant'  },
      { start: 164, end: 179, label: 'Layer B final cluster E2 (16 bytes)',                    status: 'candidate' },
      { start: 180, end: 184, label: 'Tail padding',                                           status: 'constant'  },
    ],
  },

  'wave-2': {
    bodyBytes: 1044,
    controls: [
      { label: 'Slot 0 drawbars (9 bars, NE6 nibble encoding)',  ranges: [{ start: 143, end: 147 }] },
      { label: 'Slot 1 drawbars (9 bars, NE6 nibble encoding)',  ranges: [{ start: 387, end: 391 }] },
      { label: 'Slot 2 drawbars (9 bars, NE6 nibble encoding)',  ranges: [{ start: 631, end: 635 }] },
      { label: 'Slot 3 drawbars (9 bars, NE6 nibble encoding)',  ranges: [{ start: 875, end: 879 }] },
      { label: 'Slot 0 waveform bank selector',                  ranges: [{ start: 78,  end: 78  }] },
      { label: 'Slot 0 waveform / wavetable index',              ranges: [{ start: 79,  end: 79  }] },
      { label: 'Slot 1 waveform bank selector',                  ranges: [{ start: 322, end: 322 }] },
      { label: 'Slot 1 waveform / wavetable index',              ranges: [{ start: 323, end: 323 }] },
      { label: 'Slot 2 waveform bank selector',                  ranges: [{ start: 566, end: 566 }] },
      { label: 'Slot 2 waveform / wavetable index',              ranges: [{ start: 567, end: 567 }] },
      { label: 'Slot 3 waveform bank selector',                  ranges: [{ start: 810, end: 810 }] },
      { label: 'Slot 3 waveform / wavetable index',              ranges: [{ start: 811, end: 811 }] },
    ],
    regions: [
      { start: 0,   end: 4,   label: 'Global preamble (00 00 01 2d 3f)',                    status: 'constant'  },
      { start: 5,   end: 12,  label: 'Slot 0 params A',                                    status: 'candidate' },
      { start: 13,  end: 16,  label: 'Slot 0 constant block 1',                            status: 'constant'  },
      { start: 17,  end: 35,  label: 'Slot 0 params B',                                    status: 'candidate' },
      { start: 36,  end: 39,  label: 'Slot 0 constant block 2',                            status: 'constant'  },
      { start: 40,  end: 41,  label: 'Slot 0 params C',                                    status: 'unknown'   },
      { start: 42,  end: 46,  label: 'Slot 0 constant block 3',                            status: 'constant'  },
      { start: 47,  end: 47,  label: 'Slot 0 params D',                                    status: 'unknown'   },
      { start: 48,  end: 58,  label: 'Slot 0 constant block 4',                            status: 'constant'  },
      { start: 59,  end: 59,  label: 'Slot 0 params E',                                    status: 'unknown'   },
      { start: 60,  end: 68,  label: 'Slot 0 constant block 5',                            status: 'constant'  },
      { start: 69,  end: 72,  label: 'Slot 0 params F',                                    status: 'candidate' },
      { start: 73,  end: 76,  label: 'Slot 0 constant block 6',                            status: 'constant'  },
      { start: 77,  end: 83,  label: 'Slot 0 oscillator flag + waveform bank/index',       status: 'candidate' },
      { start: 84,  end: 85,  label: 'Slot 0 constant block 7',                            status: 'constant'  },
      { start: 86,  end: 86,  label: 'Slot 0 params G',                                    status: 'unknown'   },
      { start: 87,  end: 91,  label: 'Slot 0 constant block 8',                            status: 'constant'  },
      { start: 92,  end: 92,  label: 'Slot 0 params H',                                    status: 'unknown'   },
      { start: 93,  end: 96,  label: 'Slot 0 constant block 9',                            status: 'constant'  },
      { start: 97,  end: 99,  label: 'Slot 0 params I',                                    status: 'unknown'   },
      { start: 100, end: 103, label: 'Slot 0 constant block 10',                           status: 'constant'  },
      { start: 104, end: 105, label: 'Slot 0 params J',                                    status: 'unknown'   },
      { start: 106, end: 109, label: 'Slot 0 constant block 11',                           status: 'constant'  },
      { start: 110, end: 111, label: 'Slot 0 params K',                                    status: 'unknown'   },
      { start: 112, end: 115, label: 'Slot 0 constant block 12',                           status: 'constant'  },
      { start: 116, end: 124, label: 'Slot 0 params L (wavetable morph)',                  status: 'candidate' },
      { start: 125, end: 142, label: 'Slot 0 constant block 13',                           status: 'constant'  },
      { start: 143, end: 147, label: 'Slot 0 drawbars (9 nibbles, NE6 encoding)',          status: 'confirmed' },
      { start: 148, end: 156, label: 'Slot 0 post-drawbar constant 1',                     status: 'constant'  },
      { start: 157, end: 159, label: 'Slot 0 params M',                                    status: 'unknown'   },
      { start: 160, end: 163, label: 'Slot 0 constant block 14',                           status: 'constant'  },
      { start: 164, end: 179, label: 'Slot 0 params N',                                    status: 'unknown'   },
      { start: 180, end: 183, label: 'Slot 0 constant block 15',                           status: 'constant'  },
      { start: 184, end: 186, label: 'Slot 0 params O',                                    status: 'unknown'   },
      { start: 187, end: 190, label: 'Slot 0 constant block 16',                           status: 'constant'  },
      { start: 191, end: 198, label: 'Slot 0 params P',                                    status: 'unknown'   },
      { start: 199, end: 202, label: 'Slot 0 constant block 17',                           status: 'constant'  },
      { start: 203, end: 204, label: 'Slot 0 params Q',                                    status: 'unknown'   },
      { start: 205, end: 208, label: 'Slot 0 constant block 18',                           status: 'constant'  },
      { start: 209, end: 210, label: 'Slot 0 params R',                                    status: 'unknown'   },
      { start: 211, end: 214, label: 'Slot 0 constant block 19',                           status: 'constant'  },
      { start: 215, end: 225, label: 'Slot 0 params S',                                    status: 'unknown'   },
      { start: 226, end: 229, label: 'Slot 0 constant block 20',                           status: 'constant'  },
      { start: 230, end: 231, label: 'Slot 0 params T',                                    status: 'unknown'   },
      { start: 232, end: 235, label: 'Slot 0 constant block 21',                           status: 'constant'  },
      { start: 236, end: 236, label: 'Slot 0 params U',                                    status: 'unknown'   },
      { start: 237, end: 241, label: 'Slot 0 constant block 22',                           status: 'constant'  },
      { start: 242, end: 242, label: 'Slot 0 params V',                                    status: 'unknown'   },
      { start: 243, end: 243, label: 'Slot 0 tail',                                        status: 'constant'  },
      { start: 244, end: 250, label: 'Slot 1 header prefix',                               status: 'candidate' },
      { start: 251, end: 258, label: 'Slot 1 constant 1',                                  status: 'constant'  },
      { start: 259, end: 271, label: 'Slot 1 params A',                                    status: 'candidate' },
      { start: 272, end: 281, label: 'Slot 1 constant 2',                                  status: 'constant'  },
      { start: 282, end: 283, label: 'Slot 1 params B',                                    status: 'unknown'   },
      { start: 284, end: 287, label: 'Slot 1 constant 3',                                  status: 'constant'  },
      { start: 288, end: 300, label: 'Slot 1 params C',                                    status: 'unknown'   },
      { start: 301, end: 305, label: 'Slot 1 constant 4',                                  status: 'constant'  },
      { start: 306, end: 316, label: 'Slot 1 params D',                                    status: 'unknown'   },
      { start: 317, end: 320, label: 'Slot 1 constant 5',                                  status: 'constant'  },
      { start: 321, end: 327, label: 'Slot 1 oscillator + waveform bank/index',            status: 'candidate' },
      { start: 328, end: 329, label: 'Slot 1 constant 6',                                  status: 'constant'  },
      { start: 330, end: 336, label: 'Slot 1 params E',                                    status: 'unknown'   },
      { start: 337, end: 340, label: 'Slot 1 constant 7',                                  status: 'constant'  },
      { start: 341, end: 343, label: 'Slot 1 params F',                                    status: 'unknown'   },
      { start: 344, end: 347, label: 'Slot 1 constant 8',                                  status: 'constant'  },
      { start: 348, end: 365, label: 'Slot 1 params G',                                    status: 'unknown'   },
      { start: 366, end: 374, label: 'Slot 1 constant 9',                                  status: 'constant'  },
      { start: 375, end: 377, label: 'Slot 1 params H',                                    status: 'unknown'   },
      { start: 378, end: 386, label: 'Slot 1 constant 10',                                 status: 'constant'  },
      { start: 387, end: 391, label: 'Slot 1 drawbars (9 nibbles, NE6 encoding)',          status: 'confirmed' },
      { start: 392, end: 400, label: 'Slot 1 post-drawbar constant',                       status: 'constant'  },
      { start: 401, end: 419, label: 'Slot 1 params I',                                    status: 'unknown'   },
      { start: 420, end: 421, label: 'Slot 1 constant 11',                                 status: 'constant'  },
      { start: 422, end: 438, label: 'Slot 1 params J',                                    status: 'unknown'   },
      { start: 439, end: 440, label: 'Slot 1 constant 12',                                 status: 'constant'  },
      { start: 441, end: 480, label: 'Slot 1 params K',                                    status: 'unknown'   },
      { start: 481, end: 485, label: 'Slot 1 constant 13',                                 status: 'constant'  },
      { start: 486, end: 486, label: 'Slot 1 params L',                                    status: 'unknown'   },
      { start: 487, end: 487, label: 'Slot 1 tail',                                        status: 'constant'  },
      { start: 488, end: 494, label: 'Slot 2 header prefix',                               status: 'candidate' },
      { start: 495, end: 502, label: 'Slot 2 constant 1',                                  status: 'constant'  },
      { start: 503, end: 512, label: 'Slot 2 params A',                                    status: 'candidate' },
      { start: 513, end: 524, label: 'Slot 2 constant 2',                                  status: 'constant'  },
      { start: 525, end: 527, label: 'Slot 2 params B',                                    status: 'unknown'   },
      { start: 528, end: 531, label: 'Slot 2 constant 3',                                  status: 'constant'  },
      { start: 532, end: 545, label: 'Slot 2 params C',                                    status: 'unknown'   },
      { start: 546, end: 549, label: 'Slot 2 constant 4',                                  status: 'constant'  },
      { start: 550, end: 560, label: 'Slot 2 params D',                                    status: 'unknown'   },
      { start: 561, end: 564, label: 'Slot 2 constant 5',                                  status: 'constant'  },
      { start: 565, end: 571, label: 'Slot 2 oscillator + waveform bank/index',            status: 'candidate' },
      { start: 572, end: 573, label: 'Slot 2 constant 6',                                  status: 'constant'  },
      { start: 574, end: 580, label: 'Slot 2 params E',                                    status: 'unknown'   },
      { start: 581, end: 584, label: 'Slot 2 constant 7',                                  status: 'constant'  },
      { start: 585, end: 599, label: 'Slot 2 params F',                                    status: 'unknown'   },
      { start: 600, end: 609, label: 'Slot 2 params G (wavetable morph)',                  status: 'candidate' },
      { start: 610, end: 618, label: 'Slot 2 constant 8',                                  status: 'constant'  },
      { start: 619, end: 626, label: 'Slot 2 params H',                                    status: 'unknown'   },
      { start: 627, end: 630, label: 'Slot 2 constant 9',                                  status: 'constant'  },
      { start: 631, end: 635, label: 'Slot 2 drawbars primary (9 nibbles, NE6 encoding)', status: 'confirmed' },
      { start: 636, end: 638, label: 'Slot 2 drawbars secondary (dual-drawbar candidate)', status: 'candidate' },
      { start: 639, end: 644, label: 'Slot 2 post-drawbar constant',                       status: 'constant'  },
      { start: 645, end: 663, label: 'Slot 2 params I',                                    status: 'unknown'   },
      { start: 664, end: 666, label: 'Slot 2 params J',                                    status: 'unknown'   },
      { start: 667, end: 731, label: 'Slot 2 params K tail',                               status: 'unknown'   },
      { start: 732, end: 738, label: 'Slot 3 header prefix',                               status: 'candidate' },
      { start: 739, end: 746, label: 'Slot 3 constant 1',                                  status: 'constant'  },
      { start: 747, end: 760, label: 'Slot 3 params A',                                    status: 'candidate' },
      { start: 761, end: 769, label: 'Slot 3 constant 2',                                  status: 'constant'  },
      { start: 770, end: 771, label: 'Slot 3 params B',                                    status: 'unknown'   },
      { start: 772, end: 775, label: 'Slot 3 constant 3',                                  status: 'constant'  },
      { start: 776, end: 793, label: 'Slot 3 params C',                                    status: 'unknown'   },
      { start: 794, end: 797, label: 'Slot 3 constant 4',                                  status: 'constant'  },
      { start: 798, end: 811, label: 'Slot 3 oscillator + waveform bank/index',            status: 'candidate' },
      { start: 812, end: 813, label: 'Slot 3 constant 5',                                  status: 'constant'  },
      { start: 814, end: 818, label: 'Slot 3 params D',                                    status: 'unknown'   },
      { start: 819, end: 828, label: 'Slot 3 constant 6',                                  status: 'constant'  },
      { start: 829, end: 858, label: 'Slot 3 params E',                                    status: 'unknown'   },
      { start: 859, end: 863, label: 'Slot 3 constant 7',                                  status: 'constant'  },
      { start: 864, end: 865, label: 'Slot 3 params F',                                    status: 'unknown'   },
      { start: 866, end: 874, label: 'Slot 3 constant 8',                                  status: 'constant'  },
      { start: 875, end: 879, label: 'Slot 3 drawbars (9 nibbles, NE6 encoding)',          status: 'confirmed' },
      { start: 880, end: 888, label: 'Slot 3 post-drawbar constant',                       status: 'constant'  },
      { start: 889, end: 975, label: 'Slot 3 params G tail',                               status: 'unknown'   },
      { start: 976, end: 977, label: 'Global tail header',                                 status: 'candidate' },
      { start: 978, end: 982, label: 'Global tail constant 1',                             status: 'constant'  },
      { start: 983, end: 983, label: 'Global tail params A',                               status: 'unknown'   },
      { start: 984, end: 987, label: 'Global tail constant 2',                             status: 'constant'  },
      { start: 988, end: 992, label: 'Global tail params B',                               status: 'unknown'   },
      { start: 993, end: 999, label: 'Global tail constant 3',                             status: 'constant'  },
      { start: 1000, end: 1004, label: 'Global tail params C',                             status: 'unknown'   },
      { start: 1005, end: 1013, label: 'Global tail constant 4',                           status: 'constant'  },
      { start: 1014, end: 1015, label: 'Global tail params D',                             status: 'unknown'   },
      { start: 1016, end: 1019, label: 'Global tail constant 5',                           status: 'constant'  },
      { start: 1020, end: 1022, label: 'Global tail params E',                             status: 'unknown'   },
      { start: 1023, end: 1026, label: 'Global tail constant 6',                           status: 'constant'  },
      { start: 1027, end: 1027, label: 'Global tail params F',                             status: 'unknown'   },
      { start: 1028, end: 1030, label: 'Global tail constant 7',                           status: 'constant'  },
      { start: 1031, end: 1033, label: 'Global tail params G',                             status: 'unknown'   },
      { start: 1034, end: 1037, label: 'Global tail constant 8',                           status: 'constant'  },
      { start: 1038, end: 1038, label: 'Global tail params H',                             status: 'unknown'   },
      { start: 1039, end: 1041, label: 'Global tail constant 9',                           status: 'constant'  },
      { start: 1042, end: 1042, label: 'Global tail params I',                             status: 'unknown'   },
      { start: 1043, end: 1043, label: 'Global tail constant 10',                          status: 'constant'  },
    ],
  },

  'wave': {
    bodyBytes: 306,
    controls: [
      { label: 'Slot 1 oscillator/waveform select (enum)',          ranges: [{ start: 0,   end: 1   }] },
      { label: 'Slot 2 oscillator/waveform select (enum)',          ranges: [{ start: 140, end: 141 }] },
      { label: 'Slot 1 enum param (default 7)',                     ranges: [{ start: 45,  end: 46  }] },
      { label: 'Slot 2 enum param (default 7)',                     ranges: [{ start: 185, end: 186 }] },
      { label: 'Slot 1 stepped param (even-only steps)',            ranges: [{ start: 39,  end: 40  }] },
      { label: 'Slot 2 stepped param (even-only steps)',            ranges: [{ start: 179, end: 180 }] },
      { label: 'Slot 1 voice params (osc/filter/env/LFO, packed)',  ranges: [{ start: 0,   end: 116 }] },
      { label: 'Slot 2 voice params (mirror of slot 1, +140)',      ranges: [{ start: 140, end: 256 }] },
      { label: 'Global / FX / master tail',                         ranges: [{ start: 280, end: 290 }] },
      { label: 'CBIN body checksum (trailing)',                     ranges: [{ start: 304, end: 306 }] },
    ],
    regions: [
      { start: 0,   end: 116, label: 'Slot 1 voice block (osc/filter/env/LFO)', status: 'candidate' },
      { start: 116, end: 140, label: '',                                        status: 'constant'  },
      { start: 140, end: 256, label: 'Slot 2 voice block (parallel to slot 1)', status: 'candidate' },
      { start: 256, end: 280, label: '',                                        status: 'constant'  },
      { start: 280, end: 290, label: 'Global / FX / master tail',               status: 'candidate' },
      { start: 290, end: 303, label: '',                                        status: 'constant'  },
      { start: 303, end: 304, label: 'byte[303] near-constant flag/padding',    status: 'unknown'   },
      { start: 304, end: 306, label: 'Body checksum (uint16)',                  status: 'candidate' },
    ],
  },
};
